version: '3'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
  csv-importer:
    build:
      context: ./data-import
      dockerfile: Dockerfile
    volumes:
      - csv-importer-data:/app
    depends_on:
      - postgres
    command: ["sh", "-c", "python import_csv.py && sleep infinity"]

volumes:
  postgres-data:
  csv-importer-data: